---
# Configuration for actionlint
# See: https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels:
    # Blacksmith runners (https://blacksmith.sh)
    - blacksmith-4vcpu-ubuntu-2404
    - blacksmith-2vcpu-ubuntu-2404
    - blacksmith-8vcpu-ubuntu-2404
    - blacksmith-16vcpu-ubuntu-2404
    - blacksmith-32vcpu-ubuntu-2404
