# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Harden Runner with Preset
description: >-
  Apply step-security/harden-runner with predefined endpoint presets.
  Reduces duplication across workflows by centralizing allowed endpoints.

inputs:
  preset:
    description: |
      Endpoint preset to use. Available presets:
      - python: PyPI and GitHub
      - docker: Python + container registries
      - codecov: Python + Codecov
      - sigstore: Python + Sigstore services
      - homebrew: Python + Homebrew tap
      - tooling: Language tooling registries (Rust, npm, uv, semgrep)
      - full: All endpoints (docker + codecov + sigstore + tooling + misc)
    required: true
  policy:
    description: Egress policy (block or audit)
    required: false
    default: 'block'
  extra-endpoints:
    description: Additional endpoints to allow (space-separated)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Determine allowed endpoints
      id: endpoints
      shell: bash
      # yamllint disable rule:line-length
      run: |
        # Base GitHub endpoints (always included)
        BASE="github.com:443 api.github.com:443"

        # Preset-specific endpoints
        case "${{ inputs.preset }}" in
          python)
            PRESET_ENDPOINTS="pypi.org:443 files.pythonhosted.org:443"
            ;;
          docker)
            PRESET_ENDPOINTS="pypi.org:443 files.pythonhosted.org:443"
            PRESET_ENDPOINTS+=" ghcr.io:443 docker.io:443"
            PRESET_ENDPOINTS+=" registry-1.docker.io:443 auth.docker.io:443"
            PRESET_ENDPOINTS+=" production.cloudflare.docker.com:443"
            ;;
          codecov)
            PRESET_ENDPOINTS="pypi.org:443 files.pythonhosted.org:443"
            PRESET_ENDPOINTS+=" codecov.io:443 uploader.codecov.io:443"
            PRESET_ENDPOINTS+=" storage.googleapis.com:443"
            ;;
          sigstore)
            PRESET_ENDPOINTS="pypi.org:443 files.pythonhosted.org:443"
            PRESET_ENDPOINTS+=" fulcio.sigstore.dev:443 rekor.sigstore.dev:443"
            PRESET_ENDPOINTS+=" tuf-repo-cdn.sigstore.dev:443"
            ;;
          homebrew)
            PRESET_ENDPOINTS="pypi.org:443 files.pythonhosted.org:443"
            PRESET_ENDPOINTS+=" formulae.brew.sh:443 homebrew.bintray.com:443"
            PRESET_ENDPOINTS+=" ghcr.io:443"
            ;;
          tooling)
            # Language tooling registries (Rust, npm, Python tooling, security)
            PRESET_ENDPOINTS="pypi.org:443 files.pythonhosted.org:443"
            # Rust
            PRESET_ENDPOINTS+=" static.rust-lang.org:443 sh.rustup.rs:443"
            PRESET_ENDPOINTS+=" crates.io:443 static.crates.io:443 index.crates.io:443"
            # JavaScript/Node
            PRESET_ENDPOINTS+=" bun.sh:443 registry.npmjs.org:443"
            # Python tooling (uv, ruff)
            PRESET_ENDPOINTS+=" astral.sh:443"
            # Security tools
            PRESET_ENDPOINTS+=" semgrep.dev:443"
            # System packages
            PRESET_ENDPOINTS+=" deb.debian.org:80"
            ;;
          full)
            # All endpoints: docker + codecov + sigstore + tooling + misc
            PRESET_ENDPOINTS="pypi.org:443 files.pythonhosted.org:443"
            # Container registries
            PRESET_ENDPOINTS+=" ghcr.io:443 pkg-containers.githubusercontent.com:443"
            PRESET_ENDPOINTS+=" docker.io:443 registry-1.docker.io:443"
            PRESET_ENDPOINTS+=" auth.docker.io:443 production.cloudflare.docker.com:443"
            # Codecov
            PRESET_ENDPOINTS+=" codecov.io:443 uploader.codecov.io:443"
            PRESET_ENDPOINTS+=" storage.googleapis.com:443 pings.codecov.com:443"
            # Sigstore
            PRESET_ENDPOINTS+=" fulcio.sigstore.dev:443 rekor.sigstore.dev:443"
            PRESET_ENDPOINTS+=" tuf-repo-cdn.sigstore.dev:443"
            # GitHub assets
            PRESET_ENDPOINTS+=" uploads.github.com:443 codeload.github.com:443"
            PRESET_ENDPOINTS+=" objects.githubusercontent.com:443"
            PRESET_ENDPOINTS+=" release-assets.githubusercontent.com:443"
            # Rust
            PRESET_ENDPOINTS+=" static.rust-lang.org:443 sh.rustup.rs:443"
            PRESET_ENDPOINTS+=" crates.io:443 static.crates.io:443 index.crates.io:443"
            # JavaScript/Node
            PRESET_ENDPOINTS+=" bun.sh:443 registry.npmjs.org:443"
            # Python tooling (uv, ruff)
            PRESET_ENDPOINTS+=" astral.sh:443"
            # Security tools
            PRESET_ENDPOINTS+=" semgrep.dev:443"
            # System packages
            PRESET_ENDPOINTS+=" deb.debian.org:80"
            # Homebrew
            PRESET_ENDPOINTS+=" formulae.brew.sh:443 homebrew.bintray.com:443"
            # Badges
            PRESET_ENDPOINTS+=" img.shields.io:443"
            ;;
          *)
            echo "::error::Unknown preset: ${{ inputs.preset }}"
            exit 1
            ;;
        esac

        # Combine all endpoints
        EXTRA="${{ inputs.extra-endpoints }}"
        ALL_ENDPOINTS="$BASE $PRESET_ENDPOINTS $EXTRA"

        # Format for harden-runner
        FORMATTED=$(echo "$ALL_ENDPOINTS" | tr ' ' '\n' | sort -u | \
          grep -v '^$' | tr '\n' ' ')
        echo "endpoints=$FORMATTED" >> "$GITHUB_OUTPUT"
      # yamllint enable rule:line-length

    - name: Harden Runner
      uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9
      with:
        egress-policy: ${{ inputs.policy }}
        allowed-endpoints: ${{ steps.endpoints.outputs.endpoints }}
