# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Resolve Tools Image
description: >-
  Detect tool file changes and conditionally build a fresh tools image for PR
  testing. Outputs the appropriate tools image tag to use for Docker builds.
inputs:
  push:
    description: Whether to push the built image to GHCR (false for fork PRs)
    required: false
    default: 'true'
  registry:
    description: Container registry for the tools image
    required: false
    default: ghcr.io
  image-name:
    description: Full image name without tag (for pushing new PR images)
    required: false
    default: ghcr.io/lgtm-hq/lintro-tools
  stable-image:
    # yamllint disable-line rule:line-length
    description: Full stable image reference (may differ during migrations)
    required: false
    # yamllint disable-line rule:line-length
    default: ghcr.io/lgtm-hq/lintro-tools:latest@sha256:b3940578b3fa10215d2ba4accba89250753360ec6f34cebe2dc588694084dad4
outputs:
  image:
    description: Full tools image reference to use (either fresh pr-N or stable)
    value: ${{ steps.resolve.outputs.image }}
  changed:
    description: Whether tool files were changed and a fresh image was built
    value: ${{ steps.filter.outputs.tools_changed }}
runs:
  using: composite
  steps:
    - name: Check for tool file changes
      id: filter
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_EVENT_BEFORE: ${{ github.event.before }}
      run: |
        # Define tool-related file patterns that affect image CONTENT
        # Note: scripts/ci/tools-image-*.sh are CI helpers (tags, verify, summary)
        # and don't affect image content, so they're not included here
        TOOL_PATTERNS=(
          "Dockerfile.tools"
          "scripts/utils/install-tools.sh"
          "package.json"
          "lintro/_tool_versions.py"
        )

        tools_changed="false"

        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          # For PRs, compare base to head
          echo "Checking for tool file changes in PR..."
          changed_files=$(git diff --name-only \
            "$PR_BASE_SHA" "$PR_HEAD_SHA" 2>/dev/null || echo "")

          for pattern in "${TOOL_PATTERNS[@]}"; do
            if echo "$changed_files" | grep -q "$pattern"; then
              echo "Found tool file change matching: $pattern"
              tools_changed="true"
              break
            fi
          done
        elif [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          # For push events, check if tool files changed in the pushed commits
          echo "Checking for tool file changes in push..."
          # Get the before/after from the push event
          BEFORE_SHA="${GITHUB_EVENT_BEFORE:-}"
          if [[ -n "$BEFORE_SHA" ]] && [[ "$BEFORE_SHA" != "0000000000000000000000000000000000000000" ]]; then
            changed_files=$(git diff --name-only "$BEFORE_SHA" HEAD 2>/dev/null || echo "")
            for pattern in "${TOOL_PATTERNS[@]}"; do
              if echo "$changed_files" | grep -q "$pattern"; then
                echo "Found tool file change matching: $pattern"
                tools_changed="true"
                break
              fi
            done
          fi
        else
          echo "Event type: $GITHUB_EVENT_NAME, using stable image"
        fi

        echo "tools_changed=${tools_changed}" >> "$GITHUB_OUTPUT"
        echo "Tools changed: ${tools_changed}"

    - name: Log detection result
      shell: bash
      run: |
        if [[ "${{ steps.filter.outputs.tools_changed }}" == "true" ]]; then
          echo "::notice::Tool files changed, building fresh tools image"
        else
          echo "::notice::No tool changes, using stable image"
        fi

    - name: Set up Docker Buildx (if building)
      # yamllint disable-line rule:line-length
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'pull_request'
      # yamllint disable-line rule:line-length
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      with:
        driver: docker

    - name: Log in to GHCR (if pushing)
      # yamllint disable-line rule:line-length
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'pull_request' && inputs.push == 'true'
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push tools image
      id: build
      # yamllint disable-line rule:line-length
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'pull_request'
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        context: .
        file: Dockerfile.tools
        push: ${{ inputs.push == 'true' }}
        load: ${{ inputs.push != 'true' }}
        tags: ${{ inputs.image-name }}:pr-${{ github.event.pull_request.number }}
        # Note: GHA cache not supported with docker driver

    - name: Wait for tools image (push with changes)
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'push'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        echo "Tool files changed on push, waiting for tools-image workflow..."
        # Wait for the tools-image workflow to complete (max 10 minutes)
        MAX_ATTEMPTS=60
        ATTEMPT=0
        while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
          # Check if tools-image workflow has completed for this commit
          STATUS=$(gh run list \
            --workflow "Build - Tools Image" \
            --commit "$COMMIT_SHA" \
            --json status,conclusion \
            --jq '.[0] | "\(.status) \(.conclusion)"' 2>/dev/null || echo "not_found")

          echo "Attempt $((ATTEMPT+1))/$MAX_ATTEMPTS: tools-image workflow status: $STATUS"

          if [[ "$STATUS" == "completed success" ]]; then
            echo "Tools image workflow completed successfully!"
            break
          elif [[ "$STATUS" == "completed failure" ]] || [[ "$STATUS" == "completed cancelled" ]]; then
            echo "::warning::Tools image workflow failed or was cancelled"
            break
          fi

          ATTEMPT=$((ATTEMPT+1))
          sleep 10
        done

        if [[ $ATTEMPT -ge $MAX_ATTEMPTS ]]; then
          echo "::warning::Timed out waiting for tools-image workflow"
        fi

    - name: Resolve image tag
      id: resolve
      shell: bash
      env:
        TOOLS_CHANGED: ${{ steps.filter.outputs.tools_changed }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        IMAGE_NAME: ${{ inputs.image-name }}
        STABLE_IMAGE: ${{ inputs.stable-image }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        if [[ "$TOOLS_CHANGED" == "true" ]] \
            && [[ "$GITHUB_EVENT_NAME" == "pull_request" ]] \
            && [[ -n "$PR_NUMBER" ]]; then
          # For PRs with tool changes, use the freshly built pr-N image
          IMAGE="${IMAGE_NAME}:pr-${PR_NUMBER}"
          echo "Using fresh tools image for PR: ${IMAGE}"
        elif [[ "$TOOLS_CHANGED" == "true" ]] \
            && [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          # For push events with tool changes, use :latest tag (not pinned digest)
          # The tools-image.yml workflow will have pushed a new :latest
          IMAGE="${IMAGE_NAME}:latest"
          echo "Using latest tools image (tool files changed on push): ${IMAGE}"
        else
          # Use stable image (may be from different registry during migrations)
          IMAGE="${STABLE_IMAGE}"
          echo "Using stable tools image: ${IMAGE}"
        fi
        echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
