# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Resolve Tools Image
description: >-
  Detect tool file changes and conditionally build a fresh tools image for PR
  testing. Outputs the appropriate tools image tag to use for Docker builds.
inputs:
  push:
    description: Whether to push the built image to GHCR (false for fork PRs)
    required: false
    default: 'true'
  registry:
    description: Container registry for the tools image
    required: false
    default: ghcr.io
  image-name:
    description: Full image name without tag
    required: false
    default: ghcr.io/turbocoder13/lintro-tools
  stable-tag:
    description: Tag for the stable/latest tools image
    required: false
    # yamllint disable-line rule:line-length
    default: latest@sha256:8d0e9c9630dce2907a395f415886bd95c33a22011ba6ff6f3f5acb00f87ceeae
outputs:
  image:
    description: Full tools image reference to use (either fresh pr-N or stable)
    value: ${{ steps.resolve.outputs.image }}
  changed:
    description: Whether tool files were changed and a fresh image was built
    value: ${{ steps.filter.outputs.tools_changed }}
runs:
  using: composite
  steps:
    - name: Check for tool file changes
      id: filter
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        # Define tool-related file patterns
        TOOL_PATTERNS=(
          "Dockerfile.tools"
          "scripts/utils/install-tools.sh"
          "scripts/ci/tools-image-"
          "package.json"
          "lintro/_tool_versions.py"
        )

        tools_changed="false"

        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          # For PRs, compare base to head
          echo "Checking for tool file changes in PR..."
          changed_files=$(git diff --name-only \
            "$PR_BASE_SHA" "$PR_HEAD_SHA" 2>/dev/null || echo "")

          for pattern in "${TOOL_PATTERNS[@]}"; do
            if echo "$changed_files" | grep -q "$pattern"; then
              echo "Found tool file change matching: $pattern"
              tools_changed="true"
              break
            fi
          done
        else
          # For push/other events, no dynamic build needed
          echo "Not a pull_request event, using stable image"
        fi

        echo "tools_changed=${tools_changed}" >> "$GITHUB_OUTPUT"
        echo "Tools changed: ${tools_changed}"

    - name: Log detection result
      shell: bash
      run: |
        if [[ "${{ steps.filter.outputs.tools_changed }}" == "true" ]]; then
          echo "::notice::Tool files changed, building fresh tools image"
        else
          echo "::notice::No tool changes, using stable image"
        fi

    - name: Set up Docker Buildx (if building)
      # yamllint disable-line rule:line-length
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'pull_request'
      # yamllint disable-line rule:line-length
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      with:
        driver: docker

    - name: Log in to GHCR (if pushing)
      # yamllint disable-line rule:line-length
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'pull_request' && inputs.push == 'true'
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push tools image
      id: build
      # yamllint disable-line rule:line-length
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'pull_request'
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        context: .
        file: Dockerfile.tools
        push: ${{ inputs.push == 'true' }}
        load: ${{ inputs.push != 'true' }}
        tags: ${{ inputs.image-name }}:pr-${{ github.event.pull_request.number }}
        # Note: cache-to not supported with docker driver, cache-from still works
        cache-from: type=gha,scope=tools-image

    - name: Resolve image tag
      id: resolve
      shell: bash
      env:
        TOOLS_CHANGED: ${{ steps.filter.outputs.tools_changed }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        IMAGE_NAME: ${{ inputs.image-name }}
        STABLE_TAG: ${{ inputs.stable-tag }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        if [[ "$TOOLS_CHANGED" == "true" ]] \
            && [[ "$GITHUB_EVENT_NAME" == "pull_request" ]] \
            && [[ -n "$PR_NUMBER" ]]; then
          IMAGE="${IMAGE_NAME}:pr-${PR_NUMBER}"
          echo "Using fresh tools image: ${IMAGE}"
        else
          IMAGE="${IMAGE_NAME}:${STABLE_TAG}"
          echo "Using stable tools image: ${IMAGE}"
        fi
        echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
