# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Resolve Tools Image
description: >-
  Detect tool file changes and wait for the tools-image workflow to complete.
  Outputs the appropriate tools image tag to use for Docker builds.
  For PRs/pushes with tool changes, waits for the dedicated tools-image.yml
  workflow instead of building inline.
inputs:
  image-name:
    description: Full image name without tag (for pushing new PR images)
    required: false
    default: ghcr.io/lgtm-hq/lintro-tools
  stable-image:
    # yamllint disable-line rule:line-length
    description: Full stable image reference (may differ during migrations)
    required: false
    # yamllint disable-line rule:line-length
    default: ghcr.io/lgtm-hq/lintro-tools:latest@sha256:484d1a1db596ec731b10dccfa2531327e70d3e3ae98c66014c0e7dc17bf3a408
outputs:
  image:
    description: Full tools image reference to use (either fresh pr-N or stable)
    value: ${{ steps.resolve.outputs.image }}
  changed:
    description: Whether tool files were changed and a fresh image was built
    value: ${{ steps.filter.outputs.tools_changed }}
runs:
  using: composite
  steps:
    - name: Check for tool file changes
      id: filter
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_EVENT_BEFORE: ${{ github.event.before }}
      run: scripts/ci/tools-image-detect-changes.sh

    - name: Log detection result
      shell: bash
      env:
        TOOLS_CHANGED: ${{ steps.filter.outputs.tools_changed }}
      run: |
        if [[ "$TOOLS_CHANGED" == "true" ]]; then
          echo "::notice::Tool files changed, waiting for tools-image workflow"
        else
          echo "::notice::No tool changes, using stable image"
        fi

    - name: Wait for tools image (PR with changes)
      # yamllint disable-line rule:line-length
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'pull_request'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        EVENT_TYPE: pull_request
      run: scripts/ci/tools-image-wait.sh

    - name: Wait for tools image (push with changes)
      if: steps.filter.outputs.tools_changed == 'true' && github.event_name == 'push'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        COMMIT_SHA: ${{ github.sha }}
        EVENT_TYPE: push
      run: scripts/ci/tools-image-wait.sh

    - name: Resolve image tag
      id: resolve
      shell: bash
      env:
        TOOLS_CHANGED: ${{ steps.filter.outputs.tools_changed }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        IMAGE_NAME: ${{ inputs.image-name }}
        STABLE_IMAGE: ${{ inputs.stable-image }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: scripts/ci/tools-image-resolve.sh
