---
name: Feature request
description: Suggest an idea for Lintro
labels: [enhancement, needs-triage]
body:
  - type: input
    id: summary
    attributes:
      label: Feature summary
      placeholder: Short description
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Include example usage if helpful
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - High
        - Medium
        - Low
  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      options:
        - Simple
        - Medium
        - Complex
  - type: checkboxes
    id: compatibility
    attributes:
      label: Backward compatibility
      options:
        - label: Fully compatible
        - label: Requires config changes
        - label: Breaking change
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues
        - label: This benefits the broader community
        - label: I can help implement this
