---
name: Setup environment (Python, uv, deps)
description: >-
  Set up Python and uv with caching, install project and external tool
  dependencies via scripts, and ensure local bin is on PATH
inputs:
  python-version:
    description: Python version to use
    required: false
    default: '3.13'
runs:
  using: composite
  steps:
    - name: Install uv (with cache) and Python
      # yamllint disable-line rule:line-length
      uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6
      with:
        enable-cache: true
        python-version: ${{ inputs.python-version }}

    - name: Bootstrap environment via scripts
      shell: bash
      run: ./scripts/utils/bootstrap-env.sh
