---
name: Setup Docker (Buildx + optional login)
description: Configure Docker Buildx and optionally log in to a registry
inputs:
  login:
    description: Whether to log in to a container registry
    required: false
    default: 'false'
  registry:
    description: Registry hostname (for login)
    required: false
    default: ghcr.io
  username:
    description: Registry username
    required: false
  password:
    description: Registry password or token
    required: false
  driver:
    description: Buildx driver to use (docker or docker-container)
    required: false
    default: docker
runs:
  using: composite
  steps:
    - name: Pre Setup Docker (Buildx)
      shell: bash
      run: |
        echo "[setup-docker] Configuring Docker Buildx with driver: " \
          "${{ inputs.driver }}"
        echo "[setup-docker] Login: ${{ inputs.login }}"
        echo "[setup-docker] Registry: ${{ inputs.registry }}"
    - name: Set up Docker Buildx
      # yamllint disable-line rule:line-length
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      with:
        driver: ${{ inputs.driver }}

    - name: Log in to registry
      if: inputs.login == 'true'
      # yamllint disable-line rule:line-length
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
