---
name: Setup Docker (Buildx + optional login)
description: Configure Docker Buildx and optionally log in to a registry
inputs:
  login:
    description: Whether to log in to a container registry
    required: false
    default: 'false'
  registry:
    description: Registry hostname (for login)
    required: false
    default: ghcr.io
  username:
    description: Registry username
    required: false
  password:
    description: Registry password or token
    required: false
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      # yamllint disable-line rule:line-length
      uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203dcf6e9919ebe2d0 # v3.7.1

    - name: Log in to registry
      if: inputs.login == 'true'
      # yamllint disable-line rule:line-length
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
