---
name: Post PR Comment
description: Post a prepared comment file to the current pull request
inputs:
  file:
    description: Path to the comment file
    required: true
  marker:
    description: Marker string for previous comment deletion (optional)
    required: false
    default: ''
  merge-update:
    description: If true, edit previous comment (if found) and collapse history
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Delete previous comments (optional)
      if: inputs.marker != '' && inputs.merge-update == 'false' && github.event_name == 'pull_request'
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: scripts/ci/post-pr-delete-previous.sh "${{ inputs.marker }}"

    - name: Post comment
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        MARKER="${{ inputs.marker }}" \
        ./scripts/ci/ci-post-pr-comment.sh "${{ inputs.file }}"
