---
name: Semantic PR Title Check
description: Validate PR title against Conventional Commits and optionally comment
inputs:
  types:
    description: Newline-separated list of allowed types
    required: false
    default: |
      chore
      ci
      docs
      feat
      fix
      perf
      refactor
      revert
      style
      test
  require-scope:
    description: 'Require a scope like type(scope): subject'
    required: false
    default: 'false'
  comment-on-fail:
    description: 'Post a guidance comment on the PR when invalid'
    required: false
    default: 'true'
outputs:
  ok:
    description: 'true if the PR title is valid'
    value: ${{ steps.validate.outputs.ok }}
runs:
  using: composite
  steps:
    - name: Validate PR title
      id: validate
      shell: bash
      env:
        TYPES_INPUT: ${{ inputs.types }}
        REQUIRE_SCOPE: ${{ inputs['require-scope'] }}
        COMMENT_ON_FAIL: ${{ inputs['comment-on-fail'] }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: $GITHUB_ACTION_PATH/../../../scripts/ci/github/semantic-pr-title-check.sh
