---
name: Composite Actions Smoke Tests

'on':
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Harden and Checkout
        uses: TurboCoder13/py-lintro/.github/actions/harden-and-checkout@5d38d622f2f61f6646c3918cd8ea4e53d0020295

      - name: Setup environment via composite
        uses: TurboCoder13/py-lintro/.github/actions/setup-env@5d38d622f2f61f6646c3918cd8ea4e53d0020295

      - name: Setup Docker via composite (no login)
        uses: TurboCoder13/py-lintro/.github/actions/setup-docker@5d38d622f2f61f6646c3918cd8ea4e53d0020295

      - name: Prepare dummy comment file
        run: echo "Smoke test comment" > pr-comment.txt

      - name: Test post-pr-comment composite (safe outside PR)
        uses: TurboCoder13/py-lintro/.github/actions/post-pr-comment@5d38d622f2f61f6646c3918cd8ea4e53d0020295
        with:
          file: pr-comment.txt
          marker: ''
