---
name: Docker Build
'on':
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'scripts/docker-lintro.sh'
      - 'scripts/docker-test.sh'
      - '.github/workflows/docker.yml'
      - 'pyproject.toml'
      - 'lintro/**'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'scripts/docker-lintro.sh'
      - 'scripts/docker-test.sh'
      - '.github/workflows/docker.yml'
      - 'pyproject.toml'
      - 'lintro/**'
  workflow_dispatch:
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: py-lintro:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test Docker Image
        run: ./scripts/docker-build-test.sh
