---
name: Lintro Report

'on':
  push:
    branches: [main]
    paths:
      - '**.py'
      - '**.yml'
      - '**.yaml'
      - '**.json'
      - '**.md'
      - '**.sh'
      - 'Dockerfile'
      - 'pyproject.toml'
      - '.github/workflows/lintro-report.yml'
      - 'scripts/local-lintro.sh'
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lintro-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --dev

      - name: Run Lintro on codebase
        run: ./scripts/lintro-report-generate.sh

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lintro-report
          path: lintro-report/report.md
          retention-days: 90

  notify:
    needs: lintro-report
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Report status
        run: |
          echo "Lintro report generated successfully"
          echo "The report is available as a workflow artifact"
          echo "Download it from the Actions tab in the GitHub repository"
