---
name: Renovate
'on':
  schedule:
    # Run every day at 10:00 PM UTC
    - cron: 0 22 * * *
  workflow_dispatch: # Allow manual triggering
jobs:
  renovate:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@85b17ebd5abf43d1c34c01bd4c8dbb8d45bbc2c7 # v43.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: debug
