name: GitHub Pages

on:
  workflow_run:
    workflows: ["Test and Coverage"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download coverage artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-coverage.yml
          name: coverage-report-3.10
          path: coverage-report
          workflow_conclusion: success
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create coverage report directory
        run: |
          mkdir -p _site
          cp -r coverage-report/* _site/
          echo "<meta http-equiv=\"refresh\" content=\"0; url=index.html\">" > _site/index.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 