name: Renovate

on:
  schedule:
    # Run every day at 10:00 PM UTC
    - cron: '0 22 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug' 