---
name: Mirror bomctl to GHCR and update digest

'on':
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  mirror:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    concurrency:
      group: mirror-bomctl
      cancel-in-progress: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2
        with:
          egress-policy: block
          allowed-endpoints: ${{ vars.EGRESS_ALLOWED_ENDPOINTS_MIRROR }}
      - name: Checkout (sparse)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          sparse-checkout: |
            scripts/ci/mirror-bomctl-to-ghcr.sh
          sparse-checkout-cone-mode: false
      - name: Set up gh CLI auth
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth status || true
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Optional Docker Hub login (avoid rate limits)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login docker.io -u "$DOCKERHUB_USERNAME" --password-stdin
      - name: Mirror bomctl to GHCR and update BOMCTL_IMAGE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_PLATFORM: linux/amd64
        run: |
          bash scripts/ci/mirror-bomctl-to-ghcr.sh
