---
name: Lint Workflows

'on':
  push:
    branches: [main]
    paths:
      - .github/workflows/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install actionlint
        shell: bash
        run: |
          set -euo pipefail
          BASE_URL="https://raw.githubusercontent.com/rhysd/actionlint/main"
          SCRIPT_NAME="scripts/download-actionlint.bash"
          curl -sSfL "${BASE_URL}/${SCRIPT_NAME}" | bash -s --
          sudo mv actionlint /usr/local/bin/actionlint
          actionlint --version
      - name: Run actionlint
        shell: bash
        run: |
          set -euo pipefail
          # Fail the job on any workflow lint errors
          actionlint -color
